openapi: 3.0.3
info:
  title: Erkennung German API
  description: |-
    This describes the German API used for Erkennung.
  termsOfService: http://swagger.io/terms/
  contact:
    email: hgmtrebing@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  # - url: https://petstore3.swagger.io/api/v3
  - url: /
tags:
  - name: Articles
    description: Reference API for German Articles

paths:
  /api/v1/german/articles/get-all:
    get:
      tags:
        - Articles
      summary: Retrieve a Master List of Articles.
      description: Retrieve a Master List of German Articles.
      operationId: getAllArticles
      responses:
        '200':
          description: Successful Retrieval of German Articles.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GermanArticle'
components:
  schemas:
    GermanCase:
      type: string
      enum:
        - NOMINATIVE
        - ACCUSATIVE
        - DATIVE
        - GENITIVE
        - UNDEFINED
    GermanGender:
      type: string
      enum:
        - MASCULINE
        - FEMININE
        - NEUTER
        - UNDEFINED
    GermanNumber:
      type: string
      enum:
        - SINGULAR
        - PLURAL
        - UNDEFINED
    GermanArticleType:
      type: string
      enum:
        - DEFINITE
        - INDEFINITE
        - INDEFINITE_NEGATIVE
    GermanArticle:
      type: object
      properties:
        word: 
          type: string
          description: The actual German Article.
          example: der
        case:
          $ref: '#/components/schemas/GermanCase'
        gender:
          $ref: '#/components/schemas/GermanGender'
        number:
          $ref: '#/components/schemas/GermanNumber'
        type:
          $ref: '#/components/schemas/GermanArticleType'